import Head from "next/head"
import Image from "next/image"
import home from "../styles/Home.module.scss"

export default function Home() {
  return (
    <div className={home.container}>
      <Head>
        <title>Stuy Fission 310</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <script type="text/javascript">
          document.getElementById(&quot;vid&quot;).play();
        </script>
      </Head>

      <main className={home.main}>
        
        <div className={home.titleContainer}>
          <div className={home.vertnum}>
            <span>3</span>
            <span>1</span>
            <span>0</span>
          </div>
          <h1 className={home.title}>
            Stuy Fission
          </h1>
          <div className={home.bgBorder}>
            <video muted loop name="Video Name" className={home.bg} id="vid">
              <source src="bg.mp4" />
            </video>
          </div>
          <div className={home.subtitlecontainer}>
            <h2 className={home.subtitlel}>
              Gracious Professionalism
            </h2>
            <h2 className={home.subtitler}>
              Fortune favors the brave
            </h2>
          </div>
        </div>
        
      </main>

      <footer className={home.footer}>
        Desgined by Paul
      </footer>
    </div>
  )
}
